### PR TITLE
fix: Override OpenSSL security level to allow TLSv1 connections

### PR DESCRIPTION
**Pull request by ngreatorex**
## PR Checklist

- [ ] ~~Unit Tests have been added for new changes~~ no code changes
- [ ] API tests have been updated if applicable
- [ ] ~~All commented code has been removed~~ no code changes
- [ ] ~~If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.~~ no dependency changes

## What are you changing?

OpenSSL's default security level in Alpine prevents TLSv1 and TLSv1.1 connections from being made to TLS endpoints by default. In order to still support the legacy versions of AMT, this PR changes the default cipher string to also set the security level to 0.

## Anything the reviewer should know when reviewing this PR?

I haven't added any unit tests as no real code has changed, just the cipher list.

### CODE REVIEW

**Comment by ngreatorex** [comment]
Modified the commit message to fit with guidelines

**Comment by ngreatorex** [comment]
I seem to have confused CodeCov with the fact that I originally opened this PR with a commit based on the wrong branch and later force pushed a rebase onto the correct branch.

**Comment by rsdmike** [comment]
Hey @ngreatorex , We're thinking that we make this a configurable option outside of hardcoding it -- allowing us to stick to a more secure default. Would that work for ya?

**Comment by ngreatorex** [comment]
You can, sure. 

However, `legacySupportCiphers` only gets used if you are configuring `minVersion` to TLSv1 or TLSv1.1 (which is done by default in order to support older AMT versions). Without this change, using a `minVersion` of TLSv1 or TLSv1.1 is broken on any linux distro that uses OpenSSL v3.1 or above, unless you manually modify `openssl.cnf`. This is due to [this commit](https://github.com/openssl/openssl/commit/7bf2e4d7f0c7ae19b7a8c416910886a7171e9820) to OpenSSL. 

I have confirmed it definintely doesn't work without my patch on the version of Alpine used in the Docker image built by the Dockerfile in this repo.

**Review by rsdmike — APPROVED** [review]
We'll go ahead and leave it like this for now. Thanks for the PR!

**Pull request merged**
