### PR TITLE
feat: adding AMT Alarm Clock APIs to MPS

### PR DESCRIPTION
**Pull request by orinem**
- [X ] Unit Tests have been added for new changes
- [X ] API tests have been updated if applicable
- [ X] All commented code has been removed

## What are you changing?
Adding APIs for the AMT Alarm Clock Service.

## Anything the reviewer should know when reviewing this PR?

Very brief API synopsis:

### GET /api/v1/amt/alarmOccurrences{guid}

Gets a list of alarm occurrences.  Returns an array of IPS_AlarmClockOccurrence, an empty array if there are none.  "Interval" isn't returned if not set.

Failures:

```
HTTP code 400: { error: "Incorrect URI or Bad Request", errorDescription: "more detailed description" }
HTTP code 500: { error: "Internal Server Error", errorDescription: "Exception during alarm occurrences request" }
```

Example successful return:

```
HTTP code 200
[
  {
    DeleteOnCompletion: true,
    ElementName: 'Instance Name',
    InstanceID: 'Instance',
    StartTime: {
      Datetime: '2022-12-31T23:59:00Z'
    }
  },
  {
    DeleteOnCompletion: true,
    ElementName: 'Instance Name 2',
    InstanceID: 'Instance2',
    StartTime: {
      Datetime: '2023-12-31T23:59:00Z'
    }
  }
```

### POST /api/v1/amt/alarmOccurrences{guid}

Attempts to add an alarm.  The body of the request must be an IPS_AlarmClockOccurrence.  The ElementName and StartTime properties are required.  Interval defaults to none i.e. the alarm will fire once.  DeleteOnCompletion defaults to true.  InstanceID defaults to the same as ElementName.  On success, it returns:

```
{ status: "SUCCESS", ReturnValue: 0 }
```

Failures:
```
HTTP code 400: { error: "Incorrect URI or Bad Request", errorDescription: "more detailed description" }
HTTP code 500: { error: "Internal Server Error", errorDescription: "Exception during alarm occurrences request" }
```

### DELETE /api/v1/amt/alarmOccurrences{guid}

Attempts to delete an alarm.  The body of the request must contain the instance ID of the alarm to be deleted:

```
{ Name: 'Alarm Instance Name' }
```

On success, it returns:

```
{ status: "SUCCESS" }
```

Failures:

```
HTTP code 400: { error: "Incorrect URI or Bad Request", errorDescription: "more detailed description" }
HTTP code 404: { error: "Alarm instance not found", errorDescription: "more detailed description" }
HTTP code 500: { error: "Internal Server Error", errorDescription: "Exception during alarm occurrences request" }
```

### If the there are associated PRs in other repositories, please link them here 

It requires the following change to wsman-messages:

[wsman-messages dependency
](https://github.com/open-amt-cloud-toolkit/wsman-messages/pull/180)

### CODE REVIEW

**Comment by orinem** [comment]
It's working as far as this code is concerned.

However, it appears that AMT fails chunked requests over CIRA if the final ```0\r\n\r\n``` is split between writes to the channel.  This means that certain alarm names fail, for example, "Alarm Instance 3" will fail, but "Alarm Instance" will succeed as will "ZAlarm Instance 3".

In addition in the failure case, a 400 error is returned with no body.  parseBody() in parseWSManResponseBody.ts throws an exception which is rather difficult to track down since the 'standard' exception handlers don't log a stack trace.

I suspect that always insisting there are at least 5 characters more to send when splitting writes will fix this problem, but have not yet tested this.

I added some silly level log traces to track this down.  Here is an example:

```
2022-08-01T18:54:20.977Z silly: writing: ^^@^@^@^C^@^@^Aóccurrence"><p:Datetime xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/common">2022-12-31T23:59:00Z</p:Datetime></s:StartTime><s:Interval xmlns:s="http://intel.com/wbem/wscim/1/ips-schema/1/IPS_AlarmClockOccurrence"><p:Interval xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/common">P0DT0H0M</p:Interval></s:Interval><s:DeleteOnCompletion xmlns:s="http://intel.com/wbem/wscim/1/ips-schema/1/IPS_AlarmClockOccurrence">true</s:DeleteOnCompletion></p:AlarmTemplate></p:AddAlarm_INPUT></Body></Envelope>^M
0
2022-08-01T18:54:20.988Z silly: MPS: CHANNEL_WINDOW_ADJUST, 16, 499, 499
2022-08-01T18:54:20.988Z silly: MPS: SendChannelData, 3
2022-08-01T18:54:20.989Z silly: writing: ^^@^@^@^C^@^@^@^D^M
^M

2022-08-01T18:54:20.995Z silly: MPS: CHANNEL_DATA, 16, 143
2022-08-01T18:54:20.997Z silly: parseBody: {
        "protocolVersion": "HTTP/1.1",
        "statusCode": 400,
        "statusMessage": "Bad Request",
        "headersSize": 143,
        "bodySize": 0,
        "headers": [
                {
                        "name": "Date",
                        "value": "Mon, 1 Aug 2022 18:54:20 GMT"
                },
                {
                        "name": "Server",
                        "value": "Intel(R) Active Management Technology 15.0.41.2142"
                },
                {
                        "name": "Content-Length",
                        "value": "0"
                }
        ]
}
2022-08-01T18:54:20.997Z error: Exception during alarm occurrences request : TypeError: Cannot read properties of undefined (reading 'text')
2022-08-01T18:54:20.998Z info: TypeError: Cannot read properties of undefined (reading 'text')
    at parseBody (/mps-microservice/dist/utils/parseWSManResponseBody.js:13:25)
```

FWIW, I used "docker logs mps_container > mps_logs" and "vi mps_logs" to 'show' the binary data that was logged.

**Comment by orinem** [comment]
Yes, preventing the split fixed the problem:
```
diff --git a/src/amt/APFProcessor.ts b/src/amt/APFProcessor.ts
index 1e74107..ba4e6be 100644
--- a/src/amt/APFProcessor.ts
+++ b/src/amt/APFProcessor.ts
@@ -164,9 +164,15 @@ const APFProcessor = {
         delete cirachannel.sendBuffer
       } else {
         // Send a part of the pending buffer
-        APFProcessor.SendChannelData(cirachannel.socket, cirachannel.amtchannelid, cirachannel.sendBuffer.substring(0, cirachannel.sendcredits))
-        cirachannel.sendBuffer = cirachannel.sendBuffer.substring(cirachannel.sendcredits)
-        cirachannel.sendcredits = 0
+        let toSend = cirachannel.sendcredits
+        if (cirachannel.sendBuffer.length - toSend < 5) {
+          toSend = cirachannel.sendBuffer.length - 5
+        }
+        if (toSend > 0) {
+          APFProcessor.SendChannelData(cirachannel.socket, cirachannel.amtchannelid, cirachannel.sendBuffer.substring(0, toSend))
+          cirachannel.sendBuffer = cirachannel.sendBuffer.substring(toSend)
+          cirachannel.sendcredits -= toSend
+        }
       }
     }
     return 9
```

There may be other random failures caused by this issue!

**Comment by orinem** [comment]
It's ready to go with the caveat that setting an alarm may fail pending the following issue being fixed: https://github.com/open-amt-cloud-toolkit/mps/issues/662

**Comment by matt-primrose** [comment]
@orinem we have merged your wsman-messages changes and it has been released as 2.4.0.  Can you update the package.json and package-lock.json files to have wsman-messages: "^2.4.0".  This should clear up the issues on the PR checks.

I've tested your changes on my deployment and, except for the items you mentioned, seems to work well.  I'm ready to approve.

**Comment by orinem** [comment]
@matt-primrose I was working on that.  I just pushed the change.

**Review by matt-primrose — APPROVED** [review]

**Pull request merged**
