### PR TITLE
refactor(mps): made secret manager hot-swappable

### PR DESCRIPTION
**Pull request by lunad-bsquare**
## PR Checklist

- [x] Unit Tests have been added for new changes
- [x] API tests have been updated if applicable
- [x] All commented code has been removed
- [x] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

The secret manager has been reworked so that it can be swapped out at run-time, using exactly the same mechanism as the DB provider. This will allow the secret manager to be swapped out without requiring changes to the existing codebase (which will help in keeping up-to-date).

A new config parameter has been added:
- `secrets_provider`
  - Follows the same pattern as `db_provider`
  - Defaults to `vault`

## Anything the reviewer should know when reviewing this PR?
I've noticed that the current DB factory doesn't cache the DB instance despite having logic to handle it, is this intentional? If not, I can patch in a fix using similar logic that the secret manager factory uses.

### CODE REVIEW

**Comment by rsdmike** [comment]
Hey @lunad-bsquare! Thanks for the PR, excited to to look at this. We have some rigorous commit styling, you nailed the conventional commit, but --- you'll have to squash your changes and get rid of the commit msg that doesn't conform.

**Comment by lunad-bsquare** [comment]
I am also looking to do this change for [open-amt-cloud-toolkit/rps](https://github.com/open-amt-cloud-toolkit/rps), however that service is quite different and changing it to construct the secret manager service asynchronously might be a challenge. I'll leave it for now until there's some idea on how to progress.

**Comment by lunad-bsquare** [comment]
> Hey @lunad-bsquare! Thanks for the PR, excited to to look at this. We have some rigorous commit styling, you nailed the conventional commit, but --- you'll have to squash your changes and get rid of the commit msg that doesn't conform.

I've had a go at this, it is better?

**Comment by lunad-bsquare** [comment]
The 'validate pr and commits' step seems to be failing due to a git error, and not due to issues in the commit message. Any idea as to what is going on?

**Comment by rsdmike** [comment]
Hey @lunad-bsquare,i've finally had a chance to look at this and it looks good. If you could resolve the merge conflicts, i'll approve and get it merged.

**Review by rsdmike — APPROVED** [review]

**Review by rsdmike — APPROVED** [review]

**Pull request closed without merging**
