### PR TITLE
fix(mps): mps would not start with tls_offload set to true - resolves #288

### LINKED ISSUE #288: MPS won't start when `tls_offload` is set to true or `https` is set to false
Steps to reproduce 

On .mpsrc set these values
```
"https": false,
"tls_offload": true,
```

Run MPS, it will exit

### PR DESCRIPTION
**Pull request by lobando**

### CODE REVIEW

**Comment by rsdmike** [comment]
hey @lobando , looks like you just need to fix the linting issues. You can do this automatically by running `npm run lin -- --fix` and then amending your commits. 

Thanks!

**Comment by lobando** [comment]
I missed that one. It's fixed now.

**Comment by rsdmike** [comment]
@lobando one more! Looks we got a conflict, can fix that and then we can get it merged in. Thanks!

**Review by rsdmike — APPROVED** [review]

**Comment by lobando** [comment]
> @lobando one more! Looks we got a conflict, can you fix that and then we can get it merged in. Thanks!

done. thanks

**Comment by rsdmike** [comment]
Closing in favor of #315 due to merge issue. Thanks Luis!

**Pull request closed without merging**
